/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.18 .\public\models\Frame2.glb -k 
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export function Model(props) {
  const { nodes, materials } = useGLTF('/Frame2.glb')
  return (
    <group {...props} dispose={null}>
      <group name="Empty" position={[1.444, 1.66, -2.026]} rotation={[Math.PI / 2, 0, 0]}>
        <group name="Node001" position={[0.014, -0.057, 0.11]} rotation={[1.621, -0.025, -3.14]} scale={[1.58, 1.883, 1.009]}>
          <mesh name="Node-Mesh" geometry={nodes['Node-Mesh'].geometry} material={materials['mat21.001']} />
          <mesh name="Node-Mesh_1" geometry={nodes['Node-Mesh_1'].geometry} material={materials['mat15.001']} />
          <mesh name="Node-Mesh_2" geometry={nodes['Node-Mesh_2'].geometry} material={materials.mat24} />
        </group>
        <mesh name="Node003" geometry={nodes.Node003.geometry} material={materials['mat22.001']} position={[0.014, -0.057, 0.11]} rotation={[1.621, -0.025, -3.14]} scale={[1.58, 1.883, 1.009]} />
      </group>
    </group>
  )
}

useGLTF.preload('/Frame2.glb')
